package br.com.avaliacao.desempenho.identidadeacesso.domain.model;

/** Permissões confirmadas; o código deve permanecer igual ao catálogo persistido. */
public enum PlatformPermission {
  USERS_READ("USUARIOS.LER"),
  USERS_CREATE("USUARIOS.CRIAR"),
  USERS_UPDATE("USUARIOS.ALTERAR"),
  ACCESS_MANAGE("ACESSOS.GERIR"),
  BUSINESS_ACCESS_MANAGE("ACESSOS.NEGOCIO.GERIR"),
  ASSESSMENTS_EVALUATE_LINKED("AVALIACOES.AVALIAR_VINCULADOS"),
  ASSESSMENTS_VIEW_OWN_RESPONSES("AVALIACOES.VISUALIZAR_PROPRIAS_RESPOSTAS"),
  ASSESSMENTS_VIEW_ALL("AVALIACOES.VISUALIZAR_TODAS"),
  ASSESSMENTS_PUBLISH("AVALIACOES.PUBLICAR"),
  ASSESSMENTS_REOPEN("AVALIACOES.REABRIR"),
  INDICATORS_VIEW("INDICADORES.VISUALIZAR"),
  DATA_EXPORT("DADOS.EXPORTAR"),
  SELF_ASSESSMENTS_FILL_OWN("AUTOAVALIACOES.PREENCHER_PROPRIA"),
  SELF_ASSESSMENTS_SUBMIT_OWN("AUTOAVALIACOES.ENVIAR_PROPRIA"),
  SELF_ASSESSMENTS_VIEW_OWN("AUTOAVALIACOES.VISUALIZAR_PROPRIA"),
  MASTER_DATA_MANAGE("CADASTROS.GERIR"),
  CYCLES_MANAGE("CICLOS.GERIR"),
  QUESTIONNAIRES_MANAGE("QUESTIONARIOS.GERIR"),
  MANAGER_ASSIGNMENTS_MANAGE("VINCULOS_GESTOR_COLABORADOR.GERIR"),
  USER_COLLABORATOR_ASSIGNMENTS_MANAGE("VINCULOS_USUARIO_COLABORADOR.GERIR");

  private final String code;

  PlatformPermission(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
